### ISSUE TITLE
Tool should quietly ignore non Node functions

### ISSUE THREAD

**Issue by davidebbo** [christopheranderson/azure-functions-pack#11]
Repro:

- Clone https://github.com/davidebbo-test/FunctionsGitHub
- Go into `HttpNodeAzureStorage` function folder
- Run `npm install`
- Run `funpack pack ./`, which runs successfully:

```
info: Generating project files/metadata
info: Webpacking project
info: Complete!
```

However, it does seem to do the right thing:

- The files in the `.funcpack` folder don't have anything about the function's Node modules
- `function.json` is not modified

**Comment by davidebbo** [comment]
Or maybe it needs to be run app level and not function level? I just tried that, and the tool blew up:

```
info: Generating project files/metadata
error:  Error: Function HttpTriggerCSharpHello does not have a valid start file
```

Maybe it has an assumption that all functions are Node? It should be able to ignore non-Node functions.

**Comment by christopheranderson** [comment]
Ah, yeah. That's right. It has to work at the app level. .csx functions blow it up. That's a fix I can add.

**Comment by davidebbo** [comment]
I renamed to clarify what it's about.
